name: VNC Viewer on Windows

on:
  push:
    branches:
      - main

jobs:
  vnc-job:
    runs-on: windows-latest

    steps:
      - name: Install TightVNC
        run: |
          choco install tightvnc --yes

      - name: Configure and Start TightVNC Server
        run: |
          # Configure a password for VNC
          echo password123 | & 'C:\Program Files\TightVNC\tvnserver.exe' -setpasswd
          
          # Start the TightVNC Server
          Start-Process -FilePath "C:\Program Files\TightVNC\tvnserver.exe" -ArgumentList "-run"
